import React, { useEffect, useMemo, useState } from 'react';
import { Helmet } from 'react-helmet';
import { AlertCircle, ArrowRightLeft, CalendarDays, Check, Clock3, FileText, Filter, Plus, RefreshCw, Trash2, Upload, X } from 'lucide-react';
import MainLayout from '@/components/layout/MainLayout';
import BackButton from '@/components/common/BackButton';
import { Button } from '@/components/ui/button';
import { createPonto, deletePonto, fileToDataUrl, loadPonto, updatePonto } from '@/services/pontoApi';
import { useToast } from '@/components/ui/use-toast';
import { activeOccurrenceNames, scheduleTemplates } from '@/constants/operationalCatalog';

const field = 'w-full rounded-lg border border-gray-700 bg-[#181818] px-3 py-2.5 text-sm text-white outline-none focus:border-[#ff8c00]';
const weekdays = [{ id: 0, label: 'Dom' }, { id: 1, label: 'Seg' }, { id: 2, label: 'Ter' }, { id: 3, label: 'Qua' }, { id: 4, label: 'Qui' }, { id: 5, label: 'Sex' }, { id: 6, label: 'Sáb' }];
const dateText = (value) => value ? new Date(`${value}T12:00:00`).toLocaleDateString('pt-BR') : '—';
const periodDefault = () => {
  const now = new Date();
  const start = new Date(now.getFullYear(), now.getMonth() - 1, 21, 12);
  const end = new Date(now.getFullYear(), now.getMonth(), 20, 12);
  const iso = (date) => date.toISOString().slice(0, 10);
  return { startDate: iso(start), endDate: iso(end) };
};

function OccurrenceForm({ data, form, setForm, onSave, onCancel, saving }) {
  const types = activeOccurrenceNames(data);
  const permuta = form.kind.toLowerCase() === 'permuta';
  return <section className="rounded-2xl border border-gray-700 bg-[#252525] p-5 shadow-xl">
    <div className="mb-5 flex items-start justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#ff8c00]">Novo lançamento</p><h2 className="mt-1 text-lg font-bold text-white">Ocorrência, justificativa ou permuta</h2></div><button onClick={onCancel} className="rounded-lg p-2 text-gray-500 hover:bg-white/5 hover:text-white"><X className="h-5 w-5" /></button></div>
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
      <label className="text-xs text-gray-400">Colaborador<select value={form.employeeId} onChange={(e) => setForm({ ...form, employeeId: e.target.value })} className={`mt-1 ${field}`}><option value="">Selecione...</option>{data.employees.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
      <label className="text-xs text-gray-400">Data inicial<input type="date" value={form.occurrenceDate} onChange={(e) => setForm({ ...form, occurrenceDate: e.target.value })} className={`mt-1 ${field}`} /></label>
      <label className="text-xs text-gray-400">Motivo<select value={form.kind} onChange={(e) => setForm({ ...form, kind: e.target.value })} className={`mt-1 ${field}`}>{types.map((item) => <option key={item}>{item}</option>)}</select></label>
      {!permuta && <label className="text-xs text-gray-400">Data final (opcional)<input type="date" min={form.occurrenceDate} value={form.endDate} onChange={(e) => setForm({ ...form, endDate: e.target.value })} className={`mt-1 ${field}`} /></label>}
      {permuta ? <><label className="text-xs text-gray-400">Permuta com (opcional)<select value={form.relatedEmployeeId} onChange={(e) => setForm({ ...form, relatedEmployeeId: e.target.value, relatedDate: e.target.value ? form.relatedDate : '' })} className={`mt-1 ${field}`}><option value="">Sem substituto informado</option>{data.employees.filter((item) => String(item.id) !== String(form.employeeId)).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>{form.relatedEmployeeId && <label className="text-xs text-gray-400">Data do outro plantão<input type="date" value={form.relatedDate} onChange={(e) => setForm({ ...form, relatedDate: e.target.value })} className={`mt-1 ${field}`} /></label>}<div className="md:col-span-2 flex items-center gap-3 rounded-xl border border-orange-800/50 bg-orange-950/20 p-3 text-xs text-orange-200"><ArrowRightLeft className="h-5 w-5 shrink-0" />A foto é obrigatória. Se houver substituto, os plantões serão trocados após a aprovação.</div></> : <><label className="text-xs text-gray-400">Horário inicial (opcional)<input type="time" value={form.startTime} onChange={(e) => setForm({ ...form, startTime: e.target.value })} className={`mt-1 ${field}`} /></label><label className="text-xs text-gray-400">Horário final (opcional)<input type="time" value={form.endTime} onChange={(e) => setForm({ ...form, endTime: e.target.value })} className={`mt-1 ${field}`} /></label></>}
      <label className="text-xs text-gray-400 md:col-span-2 xl:col-span-4">Motivo, documento ou observação<textarea rows="3" value={form.reason} onChange={(e) => setForm({ ...form, reason: e.target.value })} placeholder="Descreva o lançamento para conferência e auditoria" className={`mt-1 resize-none ${field}`} /></label>
      <label className="cursor-pointer rounded-xl border border-dashed border-gray-600 bg-black/10 p-4 text-xs text-gray-300 md:col-span-2 xl:col-span-4"><Upload className="mr-2 inline h-4 w-4 text-[#ff8c00]"/>{form.attachmentName || (permuta ? 'Anexar foto da permuta (obrigatória)' : 'Anexar foto ou PDF (opcional)')}<input type="file" accept="image/*,application/pdf" className="hidden" onChange={async (event) => { const file = event.target.files?.[0]; if (!file) return; setForm({ ...form, attachmentDataUrl: await fileToDataUrl(file), attachmentName: file.name }); }}/></label>
    </div>
    <footer className="mt-5 flex justify-end gap-2 border-t border-gray-700 pt-4"><Button variant="outline" onClick={onCancel} className="border-gray-600 text-gray-300">Cancelar</Button><Button onClick={onSave} disabled={saving} className="bg-[#ff8c00] font-semibold text-black hover:bg-[#ff9f2e]">{saving ? 'Salvando...' : 'Salvar lançamento'}</Button></footer>
  </section>;
}

function ScheduleBuilder({ data, form, setForm, onSave, onCancel, saving }) {
  const template = scheduleTemplates.find((item) => item.id === form.templateId) || scheduleTemplates[0];
  const applyTemplate = (id) => {
    const item = scheduleTemplates.find((row) => row.id === id) || scheduleTemplates[0];
    setForm({ ...form, templateId: item.id, cycle: item.cycle, shift: item.shift, expectedStart: item.start, expectedBreakStart: item.breakStart, expectedBreakEnd: item.breakEnd, expectedEnd: item.end, workDays: item.days });
  };
  const toggleDay = (id) => setForm({ ...form, workDays: form.workDays.includes(id) ? form.workDays.filter((day) => day !== id) : [...form.workDays, id].sort() });
  return <section className="rounded-2xl border border-gray-700 bg-[#252525] p-5 shadow-xl">
    <div className="mb-5 flex items-start justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#ff8c00]">Planejador de escala</p><h2 className="mt-1 text-lg font-bold text-white">Aplicar jornada por período</h2><p className="mt-1 text-xs text-gray-500">Crie dias de trabalho e folgas automaticamente, inclusive par/ímpar no 12x36.</p></div><button onClick={onCancel} className="rounded-lg p-2 text-gray-500 hover:bg-white/5 hover:text-white"><X className="h-5 w-5" /></button></div>
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
      <label className="text-xs text-gray-400">Colaborador<select value={form.employeeId} onChange={(e) => setForm({ ...form, employeeId: e.target.value })} className={`mt-1 ${field}`}><option value="">Selecione...</option>{data.employees.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.site_name || 'Sem posto'}</option>)}</select></label>
      <label className="text-xs text-gray-400">Modelo<select value={form.templateId} onChange={(e) => applyTemplate(e.target.value)} className={`mt-1 ${field}`}>{scheduleTemplates.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
      <label className="text-xs text-gray-400">Início do período<input type="date" value={form.startDate} onChange={(e) => setForm({ ...form, startDate: e.target.value, anchorDate: form.anchorDate || e.target.value })} className={`mt-1 ${field}`} /></label>
      <label className="text-xs text-gray-400">Fim do período<input type="date" min={form.startDate} value={form.endDate} onChange={(e) => setForm({ ...form, endDate: e.target.value })} className={`mt-1 ${field}`} /></label>
      {form.cycle === '12x36' && <label className="text-xs text-gray-400">Primeiro dia trabalhado<input type="date" value={form.anchorDate} onChange={(e) => setForm({ ...form, anchorDate: e.target.value })} className={`mt-1 ${field}`} /></label>}
      <label className="text-xs text-gray-400">Entrada<input type="time" value={form.expectedStart} onChange={(e) => setForm({ ...form, expectedStart: e.target.value })} className={`mt-1 ${field}`} /></label>
      <label className="text-xs text-gray-400">Saída intervalo<input type="time" value={form.expectedBreakStart} onChange={(e) => setForm({ ...form, expectedBreakStart: e.target.value })} className={`mt-1 ${field}`} /></label>
      <label className="text-xs text-gray-400">Retorno intervalo<input type="time" value={form.expectedBreakEnd} onChange={(e) => setForm({ ...form, expectedBreakEnd: e.target.value })} className={`mt-1 ${field}`} /></label>
      <label className="text-xs text-gray-400">Saída<input type="time" value={form.expectedEnd} onChange={(e) => setForm({ ...form, expectedEnd: e.target.value })} className={`mt-1 ${field}`} /></label>
      {['44h', '5x2', 'semanal', 'personalizada'].includes(form.cycle) && <div className="md:col-span-2 xl:col-span-3"><span className="text-xs text-gray-400">Dias trabalhados</span><div className="mt-2 grid grid-cols-7 gap-1">{weekdays.map((day) => <button key={day.id} onClick={() => toggleDay(day.id)} className={`rounded-lg border px-2 py-2 text-xs font-semibold ${form.workDays.includes(day.id) ? 'border-orange-600 bg-orange-500/15 text-orange-300' : 'border-gray-700 text-gray-500'}`}>{day.label}</button>)}</div></div>}
      <label className="text-xs text-gray-400 md:col-span-2 xl:col-span-4">Observação da escala<input value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} placeholder="Ex.: escala do contrato HGG" className={`mt-1 ${field}`} /></label>
    </div>
    <div className="mt-4 flex items-center gap-2 rounded-xl border border-blue-800/40 bg-blue-950/20 p-3 text-xs text-blue-200"><CalendarDays className="h-4 w-4" />Modelo selecionado: <strong>{template.name}</strong>. As folgas aparecerão diariamente na folha como “FOLGA ESCALA”.</div>
    <footer className="mt-5 flex justify-end gap-2 border-t border-gray-700 pt-4"><Button variant="outline" onClick={onCancel} className="border-gray-600 text-gray-300">Cancelar</Button><Button onClick={onSave} disabled={saving} className="bg-[#ff8c00] font-semibold text-black hover:bg-[#ff9f2e]">{saving ? 'Aplicando...' : 'Aplicar escala ao período'}</Button></footer>
  </section>;
}

export default function LancamentoOperacional() {
  const { toast } = useToast();
  const range = useMemo(periodDefault, []);
  const [data, setData] = useState({ employees: [], sites: [], justifications: [], schedules: [], occurrenceTypes: [] });
  const [tab, setTab] = useState('occurrences');
  const [open, setOpen] = useState(false);
  const [saving, setSaving] = useState(false);
  const [filters, setFilters] = useState({ employeeId: '', status: '', kind: '', start: range.startDate, end: range.endDate });
  const [form, setForm] = useState({ employeeId: '', occurrenceDate: new Date().toISOString().slice(0, 10), endDate: '', startTime: '', endTime: '', kind: 'Ajuste de ponto', reason: '', relatedEmployeeId: '', relatedDate: '', attachmentDataUrl: '', attachmentName: '' });
  const firstTemplate = scheduleTemplates[0];
  const [schedule, setSchedule] = useState({ employeeId: '', templateId: firstTemplate.id, cycle: firstTemplate.cycle, shift: firstTemplate.shift, startDate: range.startDate, endDate: range.endDate, anchorDate: range.startDate, expectedStart: firstTemplate.start, expectedBreakStart: firstTemplate.breakStart, expectedBreakEnd: firstTemplate.breakEnd, expectedEnd: firstTemplate.end, workDays: firstTemplate.days, notes: '' });

  const refresh = async () => { try { setData(await loadPonto({ startDate: filters.start, endDate: filters.end, month: filters.end.slice(0, 7) })); } catch (error) { toast({ title: 'Erro', description: error.message, variant: 'destructive' }); } };
  useEffect(() => { refresh(); }, []);
  const typeNames = activeOccurrenceNames(data);
  const occurrences = useMemo(() => data.justifications.filter((item) => (!filters.employeeId || String(item.employee_id) === filters.employeeId) && (!filters.status || item.status === filters.status) && (!filters.kind || item.kind === filters.kind) && (!filters.start || item.occurrence_date >= filters.start) && (!filters.end || item.occurrence_date <= filters.end)), [data.justifications, filters]);
  const submitOccurrence = async () => { if (!form.employeeId || !form.occurrenceDate || !form.reason.trim()) { toast({ title: 'Dados incompletos', description: 'Selecione o colaborador, a data e descreva o motivo.', variant: 'destructive' }); return; } if (form.kind.toLowerCase() === 'permuta' && !form.attachmentDataUrl) { toast({ title: 'Foto obrigatória', description: 'Anexe a foto que comprova a permuta.', variant: 'destructive' }); return; } setSaving(true); try { await createPonto('justification', form); setOpen(false); setForm({ ...form, reason: '', relatedEmployeeId: '', relatedDate: '', attachmentDataUrl: '', attachmentName: '' }); await refresh(); toast({ title: form.kind === 'Permuta' ? 'Permuta enviada para aprovação' : 'Lançamento salvo' }); } catch (error) { toast({ title: 'Erro', description: error.message, variant: 'destructive' }); } finally { setSaving(false); } };
  const review = async (id, status) => { try { await updatePonto('justification', id, { status }); await refresh(); toast({ title: status === 'approved' ? 'Lançamento aprovado' : 'Lançamento recusado' }); } catch (error) { toast({ title: 'Erro', description: error.message, variant: 'destructive' }); } };
  const saveSchedule = async () => { setSaving(true); try { const result = await createPonto('scheduleRange', schedule); await refresh(); setOpen(false); toast({ title: 'Escala aplicada', description: `${result.saved || 0} dia(s) planejados com trabalho e folga.` }); } catch (error) { toast({ title: 'Erro', description: error.message, variant: 'destructive' }); } finally { setSaving(false); } };
  const removeSchedule = async (id) => { if (!window.confirm('Excluir esta configuração diária de escala?')) return; await deletePonto('schedule', id); await refresh(); };

  return <><Helmet><title>Gestão Operacional - Ponto Dimivig</title></Helmet><MainLayout><div className="space-y-6">
    <BackButton />
    <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[.2em] text-[#ff8c00]">Ponto e jornada</p><h1 className="mt-1 text-3xl font-bold text-white">Gestão Operacional</h1><p className="mt-1 text-sm text-gray-400">Justificativas completas, permutas, aprovações e planejamento de escalas.</p></div><Button onClick={() => setOpen(!open)} className="bg-blue-600 hover:bg-blue-700"><Plus className="mr-2 h-4 w-4" />{tab === 'occurrences' ? 'Novo lançamento' : 'Planejar escala'}</Button></div>

    <div className="grid grid-cols-2 rounded-xl border border-gray-800 bg-[#242424] p-1"><button onClick={() => { setTab('occurrences'); setOpen(false); }} className={`rounded-lg px-4 py-3 text-sm font-semibold ${tab === 'occurrences' ? 'bg-[#ff8c00] text-black' : 'text-gray-400'}`}>Ocorrências e justificativas</button><button onClick={() => { setTab('schedules'); setOpen(false); }} className={`rounded-lg px-4 py-3 text-sm font-semibold ${tab === 'schedules' ? 'bg-[#ff8c00] text-black' : 'text-gray-400'}`}>Escalas de trabalho</button></div>

    {open && tab === 'occurrences' && <OccurrenceForm data={data} form={form} setForm={setForm} onSave={submitOccurrence} onCancel={() => setOpen(false)} saving={saving} />}
    {open && tab === 'schedules' && <ScheduleBuilder data={data} form={schedule} setForm={setSchedule} onSave={saveSchedule} onCancel={() => setOpen(false)} saving={saving} />}

    {tab === 'occurrences' ? <>
      <section className="grid gap-3 rounded-xl border border-gray-800 bg-[#282828] p-4 md:grid-cols-2 xl:grid-cols-6"><div className="flex items-center gap-2 text-sm font-semibold text-gray-300"><Filter className="h-4 w-4 text-[#ff8c00]" />Filtros</div><select value={filters.employeeId} onChange={(e) => setFilters({ ...filters, employeeId: e.target.value })} className={field}><option value="">Todos os colaboradores</option>{data.employees.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select value={filters.kind} onChange={(e) => setFilters({ ...filters, kind: e.target.value })} className={field}><option value="">Todos os motivos</option>{typeNames.map((item) => <option key={item}>{item}</option>)}</select><select value={filters.status} onChange={(e) => setFilters({ ...filters, status: e.target.value })} className={field}><option value="">Todos os status</option><option value="pending">Pendente</option><option value="approved">Aprovado</option><option value="rejected">Recusado</option></select><input type="date" value={filters.start} onChange={(e) => setFilters({ ...filters, start: e.target.value })} className={field} /><div className="flex gap-2"><input type="date" value={filters.end} onChange={(e) => setFilters({ ...filters, end: e.target.value })} className={field} /><button onClick={refresh} className="rounded-lg border border-gray-700 px-3 text-blue-300"><RefreshCw className="h-4 w-4" /></button></div></section>
      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{occurrences.map((item) => <article key={item.id} className="rounded-xl border border-gray-800 bg-[#272727] p-5">
        <header className="flex items-start justify-between"><div><span className="text-xs font-semibold text-[#ff9f2e]">{item.kind}</span><h2 className="mt-1 font-bold text-white">{item.employee_name}</h2></div><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${item.status === 'approved' ? 'bg-emerald-950/40 text-emerald-300' : item.status === 'rejected' ? 'bg-red-950/40 text-red-300' : 'bg-amber-950/40 text-amber-300'}`}>{item.status === 'approved' ? 'APROVADO' : item.status === 'rejected' ? 'RECUSADO' : 'PENDENTE'}</span></header>
        <div className="mt-4 flex items-center gap-2 text-xs text-gray-400"><CalendarDays className="h-4 w-4" />{dateText(item.occurrence_date)}{item.end_date ? ` até ${dateText(item.end_date)}` : ''}{item.start_time ? ` · ${item.start_time}–${item.end_time || '…'}` : ''}</div>
        {item.kind === 'Permuta' && <div className="mt-3 flex items-center gap-2 rounded-lg border border-orange-800/40 bg-orange-950/20 p-3 text-xs text-orange-200"><ArrowRightLeft className="h-4 w-4" />{item.related_employee_name ? `${item.related_employee_name} · ${dateText(item.related_date)}` : 'Sem substituto informado'}</div>}
        <p className="mt-4 min-h-[42px] text-sm leading-relaxed text-gray-300">{item.reason}</p>
        {item.attachment_key && <a href={`/api/ponto?entity=justification-evidence&id=${item.id}`} target="_blank" rel="noreferrer" className="mt-3 inline-flex items-center gap-2 rounded-lg border border-blue-800/40 bg-blue-950/20 px-3 py-2 text-xs font-semibold text-blue-300"><FileText className="h-4 w-4"/>Abrir comprovante</a>}
        {item.status === 'pending' && <footer className="mt-4 grid grid-cols-2 gap-2 border-t border-gray-700 pt-4"><button onClick={() => review(item.id, 'rejected')} className="rounded-lg bg-red-950/30 px-3 py-2 text-xs font-semibold text-red-300"><X className="mr-1 inline h-4 w-4" />Recusar</button><button onClick={() => review(item.id, 'approved')} className="rounded-lg bg-emerald-950/30 px-3 py-2 text-xs font-semibold text-emerald-300"><Check className="mr-1 inline h-4 w-4" />Aprovar</button></footer>}
      </article>)}{!occurrences.length && <div className="col-span-full rounded-xl border border-dashed border-gray-700 p-12 text-center text-gray-500"><AlertCircle className="mx-auto mb-2 h-8 w-8" />Nenhum lançamento encontrado.</div>}</div>
    </> : <>
      <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><div className="rounded-xl border border-gray-800 bg-[#272727] p-4"><span className="text-xs uppercase text-gray-500">Dias configurados</span><strong className="mt-1 block text-2xl text-white">{data.schedules.length}</strong></div><div className="rounded-xl border border-gray-800 bg-[#272727] p-4"><span className="text-xs uppercase text-gray-500">Dias trabalhados</span><strong className="mt-1 block text-2xl text-emerald-300">{data.schedules.filter((item) => Number(item.required) !== 0).length}</strong></div><div className="rounded-xl border border-gray-800 bg-[#272727] p-4"><span className="text-xs uppercase text-gray-500">Folgas</span><strong className="mt-1 block text-2xl text-blue-300">{data.schedules.filter((item) => Number(item.required) === 0).length}</strong></div><div className="rounded-xl border border-gray-800 bg-[#272727] p-4"><span className="text-xs uppercase text-gray-500">Modelos disponíveis</span><strong className="mt-1 block text-2xl text-[#ff9f2e]">{scheduleTemplates.length}</strong></div></div>
      <section className="overflow-hidden rounded-xl border border-gray-800 bg-[#272727]"><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm text-gray-400"><thead className="bg-[#1c1c1c] text-[10px] uppercase tracking-wide text-gray-500"><tr><th className="px-4 py-3">Data</th><th className="px-4 py-3">Colaborador</th><th className="px-4 py-3">Jornada</th><th className="px-4 py-3">Situação</th><th className="px-4 py-3">Horários</th><th className="px-4 py-3">Observação</th><th className="px-4 py-3"></th></tr></thead><tbody className="divide-y divide-gray-800">{data.schedules.map((item) => <tr key={item.id}><td className="px-4 py-3 text-white">{dateText(item.work_date)}</td><td className="px-4 py-3 text-white">{item.employee_name}</td><td className="px-4 py-3">{item.shift}</td><td className="px-4 py-3"><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${Number(item.required) !== 0 ? 'bg-emerald-950/40 text-emerald-300' : 'bg-blue-950/40 text-blue-300'}`}>{Number(item.required) !== 0 ? 'TRABALHO' : 'FOLGA'}</span></td><td className="px-4 py-3"><Clock3 className="mr-1 inline h-3.5 w-3.5" />{item.expected_start} · {item.expected_break_start} · {item.expected_break_end} · {item.expected_end}</td><td className="max-w-[240px] truncate px-4 py-3" title={item.notes}>{item.notes || '—'}</td><td className="px-4 py-3"><button onClick={() => removeSchedule(item.id)} className="text-red-400"><Trash2 className="h-4 w-4" /></button></td></tr>)}{!data.schedules.length && <tr><td colSpan="7" className="p-12 text-center text-gray-500"><CalendarDays className="mx-auto mb-2 h-8 w-8" />Nenhuma escala configurada no período.</td></tr>}</tbody></table></div></section>
    </>}
  </div></MainLayout></>;
}
