"use client";

import { useEffect, useMemo, useState } from "react";

type Person = "Gustavo";
type Status = "pending" | "progress" | "done";
type Contract = { id:number; name:string; responsible:string; referenceMonth:string; ccStatus:Status; vaStatus:Status; fgtsStatus:Status; timesheetStatus:Status; notes:string; updatedAt:string };
type Event = { id:number; contractId:number; actor:string; description:string; createdAt:string; contractName:string | null };
const people: Person[] = ["Gustavo"];
const statusLabel: Record<Status,string> = { pending:"Pendente", progress:"Em andamento", done:"Concluído" };
const deliveryFields = ["ccStatus", "vaStatus", "fgtsStatus", "timesheetStatus"] as const;
const completedDeliveries = (contract: Contract) => deliveryFields.filter(field => contract[field] === "done").length;
const displayActor = (actor: string) => people.includes(actor as Person) ? actor : "Equipe";
const displayHistory = (description: string) => description.replace(/\b(?:Wert|Lucas)\b/gi, "Equipe");

function currentMonth() { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`; }

export default function ContractsManager() {
  const [contracts,setContracts]=useState<Contract[]>([]); const [events,setEvents]=useState<Event[]>([]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(""); const [month,setMonth]=useState(currentMonth()); const [person,setPerson]=useState<"Todos"|Person>("Todos"); const [actor,setActor]=useState<Person>("Gustavo"); const [showForm,setShowForm]=useState(false); const [form,setForm]=useState({name:"",responsible:"Gustavo" as Person,notes:""});
  async function load(){setLoading(true);setError("");try{const r=await fetch(`/api/contracts?month=${month}`);const data=await r.json();if(!r.ok)throw new Error(data.error);setContracts(data.contracts);setEvents(data.events);}catch(e){setError(e instanceof Error?e.message:"Não foi possível carregar os contratos.");}finally{setLoading(false)}}
  useEffect(()=>{load()},[month]);
  const visible=useMemo(()=>person==="Todos"?contracts:contracts.filter(c=>c.responsible===person),[contracts,person]);
  const totals=useMemo(()=>{const done=contracts.filter(c=>completedDeliveries(c)===deliveryFields.length).length;return{all:contracts.length,done,pending:contracts.length-done}},[contracts]);
  async function create(e:React.FormEvent){e.preventDefault();setSaving(true);setError("");try{const r=await fetch("/api/contracts",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...form,actor})});const data=await r.json();if(!r.ok)throw new Error(data.error);setShowForm(false);setForm({...form,name:"",notes:""});await load();}catch(e){setError(e instanceof Error?e.message:"Erro ao salvar.");}finally{setSaving(false)}}
  async function update(id:number,payload:Record<string,unknown>){setSaving(true);setError("");try{const r=await fetch("/api/contracts",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,actor,month,...payload})});const data=await r.json();if(!r.ok)throw new Error(data.error);await load();}catch(e){setError(e instanceof Error?e.message:"Erro ao atualizar.");}finally{setSaving(false)}}
  async function remove(id:number,name:string){if(!confirm(`Excluir o contrato ${name}? Ele será removido de todas as competências.`))return;await fetch(`/api/contracts?id=${id}`,{method:"DELETE"});await load()}
  return <>
    <section className="contracts-heading"><div><span className="section-kicker">GESTÃO CONTÍNUA</span><h1>Controle de contratos</h1><p>Cadastre uma vez e acompanhe as quatro entregas do contrato em todas as competências.</p></div><button className="btn-primary" onClick={()=>setShowForm(true)}>＋ Novo contrato</button></section>
    <section className="team-strip"><div><span>REGISTRO DE ATUALIZAÇÕES</span><strong>As alterações ficam registradas no histórico.</strong></div>{people.map(p=><button key={p} className={actor===p?"active":""} onClick={()=>setActor(p)}><b>{p[0]}</b>{p}</button>)}</section>
    <section className="contract-metrics"><article><span>▦</span><div><small>CONTRATOS CADASTRADOS</small><strong>{totals.all}</strong></div></article><article><span>✓</span><div><small>CONCLUÍDOS NESTE MÊS</small><strong>{totals.done}</strong></div></article><article><span>!</span><div><small>PENDÊNCIAS NESTE MÊS</small><strong>{totals.pending}</strong></div></article><article className="month-control"><label>COMPETÊNCIA EXIBIDA<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label></article></section>
    <section className="contracts-toolbar"><div>{(["Todos",...people] as const).map(p=><button key={p} className={person===p?"active":""} onClick={()=>setPerson(p)}>{p}{p!=="Todos"&&<b>{contracts.filter(c=>c.responsible===p).length}</b>}</button>)}</div><span>{visible.length} contrato(s) exibido(s)</span></section>
    {error&&<div className="contracts-error">{error}</div>}
    <div className="contracts-layout"><section className="contract-board">{loading?<div className="empty-contracts">Carregando contratos...</div>:visible.length===0?<div className="empty-contracts"><b>▦</b><h3>Nenhum contrato nesta seleção</h3><p>Cadastre o primeiro contrato. Ele ficará disponível automaticamente em todas as competências.</p><button onClick={()=>setShowForm(true)}>Cadastrar contrato</button></div>:visible.map(c=><ContractRow key={c.id} contract={c} saving={saving} update={update} remove={remove}/>)}</section><aside className="history-panel"><div className="history-title"><span>HISTÓRICO RECENTE</span><b>Salvo automaticamente</b></div>{events.length===0?<p className="history-empty">As atualizações aparecerão aqui.</p>:events.slice(0,10).map(e=><div className="history-item" key={e.id}><span className={`person-dot ${displayActor(e.actor).toLowerCase()}`}>{displayActor(e.actor)[0]}</span><div><strong>{e.contractName||"Contrato"}</strong><p>{displayHistory(e.description)}</p><small>{displayActor(e.actor)} · {new Date(e.createdAt+"Z").toLocaleString("pt-BR",{dateStyle:"short",timeStyle:"short"})}</small></div></div>)}</aside></div>
    {showForm&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setShowForm(false)}}><form className="contract-modal" onSubmit={create}><header><div><span>NOVO CONTRATO</span><h2>Cadastrar contrato</h2><p>Cadastre uma única vez. Ele aparecerá automaticamente em todos os meses.</p></div><button type="button" onClick={()=>setShowForm(false)}>×</button></header><label>Nome do contrato<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Ex.: HGG, ANATEL, EMBRAPA..."/></label><label>Responsável principal<select value={form.responsible} onChange={e=>setForm({...form,responsible:e.target.value as Person})}>{people.map(p=><option key={p}>{p}</option>)}</select></label><label>Observações<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Informações importantes, prazos ou particularidades..."/></label><footer><button type="button" onClick={()=>setShowForm(false)}>Cancelar</button><button className="btn-primary" disabled={saving}>{saving?"Salvando...":"Salvar em todas as competências"}</button></footer></form></div>}
  </>;
}

function ContractRow({contract,saving,update,remove}:{contract:Contract;saving:boolean;update:(id:number,p:Record<string,unknown>)=>void;remove:(id:number,n:string)=>void}){const done=completedDeliveries(contract);return <article className="contract-row"><div className="contract-main"><div className="contract-avatar">{contract.name.slice(0,2).toUpperCase()}</div><div><h3>{contract.name}</h3><span>Competência {contract.referenceMonth.split("-").reverse().join("/")}</span>{contract.notes&&<p>{contract.notes}</p>}</div></div><div className="owner-select"><small>RESPONSÁVEL</small><select aria-label={`Responsável por ${contract.name}`} value={contract.responsible} disabled={saving} onChange={e=>update(contract.id,{responsible:e.target.value})}>{!people.includes(contract.responsible as Person)&&<option value={contract.responsible} disabled>Equipe</option>}{people.map(p=><option key={p}>{p}</option>)}</select></div><div className="task-statuses"><StatusSelect label="CC + Comprovante" value={contract.ccStatus} disabled={saving} onChange={status=>update(contract.id,{field:"ccStatus",status})}/><StatusSelect label="Vale-Alimentação" value={contract.vaStatus} disabled={saving} onChange={status=>update(contract.id,{field:"vaStatus",status})}/><StatusSelect label="FGTS" value={contract.fgtsStatus} disabled={saving} onChange={status=>update(contract.id,{field:"fgtsStatus",status})}/><StatusSelect label="Folha de Ponto" value={contract.timesheetStatus} disabled={saving} onChange={status=>update(contract.id,{field:"timesheetStatus",status})}/></div><div className="contract-progress"><strong>{done}/{deliveryFields.length}</strong><span><i style={{width:`${done/deliveryFields.length*100}%`}}/></span><small>{done===deliveryFields.length?"Finalizado":"Progresso"}</small></div><button className="contract-delete" disabled={saving} onClick={()=>remove(contract.id,contract.name)} title="Excluir contrato">⋮</button></article>}
function StatusSelect({label,value,disabled,onChange}:{label:string;value:Status;disabled:boolean;onChange:(v:Status)=>void}){return <label><span>{label}</span><select className={value} value={value} disabled={disabled} onChange={e=>onChange(e.target.value as Status)}><option value="pending">○ {statusLabel.pending}</option><option value="progress">◐ {statusLabel.progress}</option><option value="done">● {statusLabel.done}</option></select></label>}
